name: Mac make CI

on:
  push:
    paths-ignore:
    - 'include/wx/dfb/**'
    - 'include/wx/gtk/**'
    - 'include/wx/gtk1/**'
    - 'include/wx/motif/**'
    - 'include/wx/msw/**'
    - 'include/wx/x11/**'
    - 'src/dfb/**'
    - 'src/gtk/**'
    - 'src/gtk1/**'
    - 'src/motif/**'
    - 'src/msw/**'
    - 'src/x11/**'
    - 'build/tools/appveyor*.bat'
    - 'build/tools/travis-ci.sh'
    - 'distrib/**'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    defaults:
      run:
        shell: /usr/bin/arch -arch ${{ matrix.arch }} /bin/bash -l {0}

    runs-on: self-hosted
    
    name: ${{ matrix.build }}, arch ${{ matrix.arch }}, cxx${{ matrix.cxx }}

    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      NSUnbufferedIO: YES

    strategy:
      fail-fast: false
      matrix:
        arch: [arm64e, x86_64]
        build: [debug, release]
        cxx: [11, 17]
        include:
        - build: debug
          config: --without-liblzma --enable-debug --disable-sys-libs --with-osx_cocoa
        - build: release
          config: --without-liblzma --disable-sys-libs --with-osx_cocoa
        - cxx: 17
          cxxconfig: --with-macosx-version-min=10.12
        - cxx: 11
          cxxconfig:

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: configure
      run: mkdir -p $PWD/localbin_${{ matrix.arch }}; ./configure ${{ matrix.config }} ${{ matrix.cxxconfig }} --with-cxx=${{ matrix.cxx }} --prefix=$PWD/localbin_${{ matrix.arch }}
    - name: make
      run: make -j4
    - name: make install
      run: make install
    - name: make tests
      run: make -j4 -C tests
    - name: run tests
      run: pushd tests;./test;popd
